### ISSUE TITLE
SOA and NS records

### ISSUE THREAD

**Issue by mschirrmeister** [polaris-gslb/polaris-gslb#12]
I have 2 questions. Is it possible to set or modify the SOA record and NS records? 

I usually delete a subdomain to my GSLB infrastructure. For example `l.example.com`. So I would like to set the SOA record for those domains. I can see that there is a SOA record for the full entry from the config and it is `polaris.example.com. hostmaster.polaris.example.com. 1 600 86400 1 3600`.

And it would also be nice to configure the NS entries for the GSLB domains. Is this planned?

Thank you
Marco

**Comment by antongavrik** [comment]
I'm sorry, I'm not sure I can follow here, could you please provide more details and, maybe, examples of what you are trying to accomplish? Thank you

**Comment by mschirrmeister** [comment]
Here is a little deeper description and also a diagram what I have setup for testing with polaris.

Whole DNS resolution from a client. Generally works.

    # dig app1.omg.wpp @127.0.0.1 +short
    app1.l.omg.wpp.
    10.10.2.3

Querying authoritative dns servers for **omg.wpp** for NS records for gslb subdomain **l.omg.wpp** that resides on Polaris.

    # dig ns omg.wpp @10.10.1.10

    ;; QUESTION SECTION:
    ;l.omg.wpp.			IN	NS

    ;; AUTHORITY SECTION:
    l.omg.wpp.		3600	IN	NS	a.l.omg.wpp.
    l.omg.wpp.		3600	IN	NS	b.l.omg.wpp.

    ;; ADDITIONAL SECTION:
    a.l.omg.wpp.		3600	IN	A	10.10.1.20
    b.l.omg.wpp.		3600	IN	A	10.10.1.21

Querying authoritative dns servers (Polaris) for **l.omg.wpp** for NS records.

    # dig ns l.omg.wpp @10.10.1.20

    ;l.omg.wpp.			IN	NS
    
    #
    
There was no answer for NS records on Polaris and there is also no SOA.

    # dig soa l.omg.wpp @10.10.1.20

    ;; QUESTION SECTION:
    ;l.omg.wpp.			IN	SOA
    
    #
    
But if you query the entry that is configured in Polaris for SOA, you receive the answer. But with **`example.com`**.

    # dig soa app1.l.omg.wpp @10.10.1.20

    ;; QUESTION SECTION:
    ;app1.l.omg.wpp.			IN	SOA

    ;; ANSWER SECTION:
    app1.l.omg.wpp.		60	IN	SOA	polaris.example.com. hostmaster.polaris.example.com. 1 600 86400 1 3600
    
    #
    
What I think would be nice is that if the SOA is configurable to something else than *example.com*. And also be able to configure static DNS entries for the delegated domain `l.omg.wpp`. Basically NS records.

    l.omg.wpp.	28800  IN  NS     a.l.omg.wpp.
    l.omg.wpp.	28800  IN  NS     d.l.omg.wpp.
    l.omg.wpp.	28800  IN  SOA    d.l.omg.wpp. dnsmaster.l.omg.wpp. 2015111201 10800 900 2160000 3600

I see that more from a dns perspective. If someone troubleshoots things and does dns lookups, he might be confused if there is no SOA or if it has example.com in it and also if there are no NS records.

Polaris LB configuration.

    pools:
        app1:
            monitor: http
            monitor_params:
                use_ssl: false
                hostname: app1.omg.wpp
                url_path: /
            lb_method: twrr
            fallback: any
            members:
                10.10.2.3:
                    name: web-lb
                    weight: 3

    globalnames:
        app1.l.omg.wpp:
            pool: app1
            ttl: 5

Hope I explained it now a little better.

Diagram  
![polaris_gslb_example](https://cloud.githubusercontent.com/assets/1037177/11118000/e75f4722-893e-11e5-9dfd-be5f8a0cbd8d.png)

Thanks
Marco

**Comment by antongavrik** [comment]
Thank you for the detailed explanation. 

Polaris is not meant to be delegated a subdomain to, but only specific FQDNs and, as such, has no functionality to support this.

In the case you presented, it might mean either delegating app1.omg.wpp to Polaris or app1.l.omg.wpp with l.omg.wpp being delegated to a generic DNS server first.
 
As far as changing the hostname that comes in SOA it is already possible via /opt/polaris/etc/polaris-pdns.yaml by uncommenting/modifying the HOSTNAME attribute:

################################
# hostname to use when generating a SOA response
#
# HOSTNAME: polaris.example.com

I hope this helps.

**Comment by mschirrmeister** [comment]
Ok, thanks. Looks like I overlooked this **HOSTNAME** option. This piece works now.

But for delegation. Even if I would directly delegate *app1.omg.wpp* and any other side to the gslb dns servers. Then I would expect NS records for *app1.omg.wpp* from a dns point of view.

That would mean to create NS records for each an every delegated gslb application. To avoid this, that is why we have currently in our production gslb setup a specific subdomain delegated. The management is easier and it looks cleaner. One delegation, one set of NS records and the rest are just CNAMEs for each new app on the parent dns server.

I will live with it for now. Maybe the feature list could include an item that it is possible to configure a few static dns entries in the future.

**Comment by antongavrik** [comment]
>That would mean to create NS records for each an every delegated gslb application.

Correct, this is how it's meant to operate.

>Maybe the feature list could include an item that it is possible to configure a few static dns entries in the future.

I do see your point on having a cleaner setup, however, this does not appear to be a simple enhancement as it would require introducing zone configuration management, which isn't in scope, as assumed to be covered by a parent authoritative server.
