### ISSUE TITLE
review the applicability of stripping a trailing dot in qname 

### ISSUE THREAD

**Issue by antongavrik** [polaris-gslb/polaris-gslb#21]
A potential change in pdns json api reported in #20 is causing a trailing dot to be seen in json api qname, we might be better off attempting to strip it before the qname gets processed further.

**Comment by antongavrik** [comment]
Not applicable at this time.

**Comment by tupcakes** [comment]
What ended up being the fix for this issue?

**Comment by tupcakes** [comment]
Nevermind I figured it out. I added a root domain to the domain in the globalnames section.

**Comment by antongavrik** [comment]
https://doc.powerdns.com/authoritative/backends/remote.html states that, starting from v4.0, DNS names are sent with a trailing dot.

**Comment by mmontefl** [comment]
@antongavrik I appreciate you answering these questions. I am not sure if you are the original developer, but this solution is very cool. I am not a developer, but a Network Architect and trying this a possible solution for some clients.  The idea of using the older pDNS has me a bit concerned.

What would I have to do to use 4.x pDNS but still have Polaris function?

**Comment by mmontefl** [comment]
Also, I see dDNS has notice of "Remote Backend".  If we have multiple sites and pDNS's running is there a way to design where this no backend in the design. Sorry for my lack of expertise with open source DNS.

**Comment by antongavrik** [comment]
Try appending global names with a ".", e.g.:
```
globalnames:
    www.example.com.:
        pool: www-example
        ttl: 1
```

**Comment by mmontefl** [comment]
far enough, I'll try that now

**Comment by mmontefl** [comment]
I have polaris installed using python 3.5.6 and power dns 4.1.4. Services are running ok. I edited lb conf to run ok (after some line spacing issues were resolved) now I cant seem to get pdns to reply with an SOA record I added to  /opt/polaris/etc/polaris-pdns.yaml and systemctl restart pdns

systemctl status polaris-gslb.service = running
systemctl status pdns.service = running

Maybe due to these status below?

[root@gslb25 ~]# /opt/polaris/bin/polaris-memcache-control 127.0.0.1 get-ppdns-state
/usr/bin/env: python3: No such file or directory
[root@gslb25 ~]# /opt/polaris/bin/polaris-memcache-control get-generic-state
/usr/bin/env: python3: No such file or directory

Not sure how to edit the pdns; do I change the pdns.conf.dist?
Do I add A and NS records to  /opt/polaris/etc/polaris-pdns.yaml?

**Comment by antongavrik** [comment]
Searching the web there is some community-written documentation that might help to get started: 
https://github.com/polaris-gslb/polaris-gslb/wiki/Installation
http://www.loadbalancer.org/blog/gslb-why-global-server-load-balancers-dont-always-suck-polaris-gslb/
https://www.loadbalancer.org/blog/gslb-why-global-server-load-balancers-dont-always-suck-polaris-gslb-part-2/
http://www.loadbalancer.org/blog/loadbalancer-org-releases-a-gslb/
https://blogs.msdn.microsoft.com/mihansen/2017/10/13/open-source-private-traffic-manager-and-regional-failover/

For polaris-memcache-control issue you need to make sure python3 binary is in the shell PATH of the user running the command(root in your example).

pdns.conf.dist needs to be copied into /etc/pdns/pdns.conf (or wherever pdns config file lives on your system).

A records are derived from polaris-lb.conf, there is no way to add NS records currently.

**Comment by mmontefl** [comment]
Thanks, I have been using the lb.org as my MOP, but just replaced his python with the latest ver in that train 3.5.6 and did uplift the pdns to 4.1.4.  

I added path and all is well. I can see the status' now : )
Polaris and pdns are running and seem healthy. I know I have the pdns.conf in properly dir as I am able to toggle log and restart services is see its affect.

I am just stuck on the creation of the DNS records. You say that NS's arent supported. But how do I make the A records? or interact with the larger DNS for that name space?
seems the pdns.ymal would point to the SOA? Gather thats all that file does?

I can do a "dig -type=any google.com 127.0.0.1" and get a result. But when I do for my domain, I see the hosted SOA as well and no local records. Can you share where in the lb.yaml exactly that correlates with the creation of an A record?

**Comment by mmontefl** [comment]
missed this one, this seems to have a lot of info, running this down now. 
https://www.loadbalancer.org/blog/loadbalancer-org-releases-a-gslb/

**Comment by nitinagarwal1982** [comment]
@mmontefl Are you able to solve the problem?

I stuck on the same point you mentioned and raised query for the same:
https://github.com/polaris-gslb/polaris-gslb/issues/57
