### ISSUE TITLE
How to add multiple domains and sub-domains?

### ISSUE THREAD

**Issue by jsclub75** [polaris-gslb/polaris-gslb#26]
I want to add a number of domains and subdomains in polaris-lb.yaml
Please let me know.

**Comment by antongavrik** [comment]
There is an example in https://github.com/polaris-gslb/polaris-gslb/wiki/Overview

**Comment by jsclub75** [comment]
Thank you for living the answer.

One sub-domain has been used to apply the Polaris.
I do not know, how to use multi-domain(sub-domain)
No experience using the json api.
Let me explain in more detail.
