### ISSUE TITLE
can't work,why?

### ISSUE THREAD

**Issue by paulyue** [polaris-gslb/polaris-gslb#30]
Hello,
I have tried polaris-gslb with pdns3.4.9 and Python3.4.5. Installation is fine. But DNS don't work. 
"status": true I don't know why it's false

/opt/polaris/bin/polaris-memcache-control get-generic-state
{
    "timestamp": 1478168302.3423028,
    "pools": {
        "www-example2": {
            "name": "www-example2",
            "fallback": "any",
            "lb_method": "fogroup",
            "members": [
                {
                    "last_probe_issued_time": 1478168301.3214195,
                    "ip": "114.215.87.85",
                    "region": "None",
                    "name": "www2-dc1",
                    "retries_left": 0,
                    "status_reason": "404 Not Found",
                    "status": false,
                    "weight": 1
                }
            ],
            "max_addrs_returned": 1,
            "last_status": false,
            "monitor": {
                "port": 80,
                "interval": 10,
                "hostname": "www.appextest.com",
                "use_ssl": false,
                "name": "http",
                "url_path": "/health2.html",
                "retries": 2,
                "timeout": 5
            }
        },
        "www-example": {
            "name": "www-example",
            "fallback": "any",
            "lb_method": "fogroup",
            "members": [
                {
                    "last_probe_issued_time": 1478168301.321435,
                    "ip": "114.215.87.85",
                    "region": "None",
                    "name": "www1-dc1",
                    "retries_left": 0,
                    "status_reason": "ConnectionRefusedError [Errno 111] Connection refused during socket.connect()",
                    "status": false,
                    "weight": 1
                }
            ],
            "max_addrs_returned": 1,
            "last_status": false,
            "monitor": {
                "port": 443,
                "interval": 10,
                "hostname": "www.example1211.com",
                "use_ssl": true,
                "name": "http",
                "url_path": "/health.html",
                "retries": 2,
                "timeout": 5
            }
        }
    },
    "globalnames": {
        "www.appextest.com": {
            "ttl": 1,
            "name": "www.appextest.com",
            "pool_name": "www-example2"
        },
        "www.example1211.com": {
            "ttl": 1,
            "name": "www.example1211.com",
            "pool_name": "www-example"
        }
    }
}

**Comment by antongavrik** [comment]
Can you please provide more details, examples on what exactly doesn't work?

**Comment by paulyue** [comment]
my vps, CentOS 6.5, installation details: 

# install PDNS
	yum install -y epel-release 
	yum install -y gcc gcc-c++ make
	yum install -y boost boost-devel boost-doc

	PDNS_VERSION=3.4.9
	wget -P /tmp/ https://downloads.powerdns.com/releases/pdns-${PDNS_VERSION}.tar.bz2
	tar -xvf /tmp/pdns-${PDNS_VERSION}.tar.bz2 -C /tmp
	cd /tmp/pdns-${PDNS_VERSION}
	./configure --with-modules="remote" && make -j 4 && make install

# install pdns init script
	cp pdns/pdns /etc/init.d/
# add pdns to start-up 
	chkconfig --add pdns

# install memcached
	yum -y install memcached
	/etc/init.d/memcached start

# install python 3.4.5
	yum install -y zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel 
	wget https://www.python.org/ftp/python/3.4.5/Python-3.4.5.tgz
	tar xf Python-3.4.5.tgz -C /usr/local/src/
	cd /usr/local/src/Python-3.4.5/
	./configure --prefix=/usr/local/python3.4
	make -j4 && make install

Edit ~/.bash_profile, change PATH=$PATH:$HOME/bin to PATH=$PATH:$HOME/bin:/usr/local/python3.4/bin

	. ~/.bash_profile

# install Polaris
        git clone https://github.com/polaris-gslb/polaris-gslb.git
     	cd polaris-gslb
	python3.4 setup.py install

The following files are created correctly:
/opt/polaris/
├── bin
│   ├── check-pdns
│   ├── polaris-health
│   ├── polaris-health-control
│   ├── polaris-memcache-control
│   ├── polaris-pdns
│   └── polaris-pdns-control
├── etc
│   ├── pdns.conf.dist
│   ├── polaris-health.yaml.dist
│   ├── polaris-lb.yaml.dist
│   ├── polaris-pdns.yaml.dist
│   └── polaris-topology.yaml.dist
└── run

Ensure /etc/default/polaris has a correct PATH to python executable, e.g.:
export PATH=$PATH:/usr/local/python3.4/bin
export POLARIS_INSTALL_PREFIX=/opt/polaris

# Install the Polaris-specific PDNS configuration file
	cp /opt/polaris/etc/pdns.conf.dist /usr/local/etc/pdns.conf

Copy /opt/polaris/etc/*.dist files into *.yaml or create new ones and configure:
polaris-lb.yaml 			- LB configuration
polaris-topology.yaml - topology configuration
polaris-health.yaml	 	- Polaris health general parameters
polaris-pdns.yaml 		- Polaris PDNS general parameters

# run PDNS
	/etc/init.d/pdns start
	/opt/polaris/bin/polaris-health start

**Comment by antongavrik** [comment]
What issue are you seeing?

**Comment by paulyue** [comment]
/opt/polaris/bin/polaris-memcache-control get-generic-state 

"status_reason": "404 Not Found",
"status": false,

I see the others guys will get
"status_reason": "mirror passed",
"status": true,

I want to know what's wrong with my installation.Thanks.

**Comment by paulyue** [comment]
The powerDNS don't work. I can't get "www.example1211.com"'s ip when i set DNS server as powerDNS.

**Comment by antongavrik** [comment]
What does "/opt/polaris/bin/polaris-memcache-control get-ppdns-state" return?

**Comment by paulyue** [comment]
[root@iZ28njy3yzoZ ~]# /opt/polaris/bin/polaris-memcache-control get-ppdns-state
{
    "pools": {
        "www-example": {
            "lb_method": "fogroup",
            "status": false,
            "fallback": "any",
            "dist_tables": {
                "_default": {
                    "index": 0,
                    "rotation": [
                        "114.215.87.85"
                    ],
                    "num_unique_addrs": 1
                }
            },
            "max_addrs_returned": 1
        },
        "www-example2": {
            "lb_method": "fogroup",
            "status": false,
            "fallback": "any",
            "dist_tables": {
                "_default": {
                    "index": 0,
                    "rotation": [
                        "114.215.87.85"
                    ],
                    "num_unique_addrs": 1
                }
            },
            "max_addrs_returned": 1
        }
    },
    "timestamp": 1478168673.357057,
    "globalnames": {
        "www.example1211.com": {
            "ttl": 1,
            "pool_name": "www-example"
        },
        "www.appextest.com": {
            "ttl": 1,
            "pool_name": "www-example2"
        }
    }
}

**Comment by antongavrik** [comment]
What output do you get when you dig against the Polaris IP addr, e.g. "dig @<polaris_addr> www..example1211.com" ?

**Comment by paulyue** [comment]
C:\Users\xx>dig @114.215.87.85 www.example1211.com

; <<>> DiG 9.10-P2 <<>> @114.215.87.85 www.example1211.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 44183
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.example1211.com.           IN      A

;; AUTHORITY SECTION:
com.                    898     IN      SOA     a.gtld-servers.net. nstld.verisign-grs.com. 1479802964 1800 900 604800 86400

;; Query time: 518 msec
;; SERVER: 114.215.87.85#53(114.215.87.85)
;; WHEN: Tue Nov 22 16:23:08  2016
;; MSG SIZE  rcvd: 121

**Comment by antongavrik** [comment]
Polaris should never return an NXDOMAIN, something must be wrong with the installation, e.g. polaris-specific pdns.conf file is not being used with PowerDNS.
