### ISSUE TITLE
Create SOA record with serial

### ISSUE THREAD

**Issue by mattjcurry** [polaris-gslb/polaris-gslb#31]
I am suspecting that many Public DNS providers are not updating their cache because the serial number of the SOA record is not getting incremented.  In fact there is no SOA record.  If I dig against polaris itsself, then everything works great, but once I start digging against google DNS, it appears that it keeps the first cached value forever.  I cranked the TTL down to 1 which gives the google record a TTL of 0 (No Cache)

**Comment by antongavrik** [comment]
Polaris does respond to SOA queries with serial hardcoded to 1. It would be good to test this further to better understand the behavior.

**Comment by antongavrik** [comment]
The upcoming release 0.5 addresses this issue by exposing all SOA fields via the configuration, in addition, when SOA_SERIAL field set to "auto" the serial will be automatically set to seconds since epoch time of the last state change.

**Comment by antongavrik** [comment]
Configurable SOA, including automatic SOA generation is added in v0.5
