### ISSUE TITLE
Any plans for a GUI monitor interface?

### ISSUE THREAD

**Issue by atielmejor** [polaris-gslb/polaris-gslb#36]
Hi Anton, great job with polaris-gslb!
I want to use it for several vhosts and when config file grows it is very difficult to perform a state check.
I'm wondering if you're planning to add an interface for state monitoring or if there's a better way to achieve this.

**Comment by antongavrik** [comment]
No GUI is planned. The state information is readily available in memcached under "polaris_health:generic_state" key, it can also be grabbed with the below command.

/opt/polaris/bin/polaris-memcache-control 127.0.0.1 get-generic-state
