### ISSUE TITLE
issue with HTTP healthcheck

### ISSUE THREAD

**Issue by john-bakker** [polaris-gslb/polaris-gslb#37]
Hi,

When I configure my HTTP healthcheck to the following :
pools:
  example1:
    monitor: http
    monitor_params:
      use_ssl: true
      hostname: www.example.com
      url_path: /
      interval: 30
      expected_codes:
      - 302

My polaris-gslb fails to start. However when I change the path that is expecting a 200, and remove the expected_codes: it works. Could you please look into this

**Comment by antongavrik** [comment]
Please provide the error produced.

/opt/polaris/bin/polaris-health start-debug
