### ISSUE TITLE
Does it support the dynamic DNS and smart DNS according to the geo location of IP?

### ISSUE THREAD

**Issue by yyh1102** [polaris-gslb/polaris-gslb#41]
Hi, i wanna use this good project as a GSLB for CDN scenario.I've read the Wiki carefully but don't find the dynamic configuration of the pools and don't know weather or not it has a smart DNS resolve according to the geo location of source IP?
Would you be so kind to give some advices for how can i solve this problems based on your project? like re-develop or have some hidden API in your project maybe?

Thanks!

**Comment by antongavrik** [comment]
No support for geo location currently. As far as pool re-configuration, changing the config yaml and restarting the health daemon has no impact on the DNS resolution.

**Comment by yyh1102** [comment]
Thanks for replying~
