### ISSUE TITLE
polaris_health.tracker: failed to write generic state to the shared memory

### ISSUE THREAD

**Issue by mattackerman808** [polaris-gslb/polaris-gslb#46]
Under high usage of polaris-health I am seeing that warning log continually. A Polaris-health restart seems to fix it for awhile and then it starts again.

I am not seeing any other symptom of this error but I am assuming it's bad as it has to do with the state tracker/change code in the tracker submodule.

I have been attempting to debug this by adding logging but nothing useful is getting returned.

I added the following:

        # push generic form of the state
        # add timestampt to the object
        generic_form['timestamp'] = STATE_TIMESTAMP
        val = self.sm.set(config.BASE['SHARED_MEM_GENERIC_STATE_KEY'],
                           generic_form)
        if val is True:
            pushes_ok += 1
        else:
            log_msg = ('failed to write generic state to the shared memory')
            LOG.warning(log_msg)
            LOG.warning(val)
            LOG.warning(config.BASE['SHARED_MEM_GENERIC_STATE_KEY'],generic_form)

And the output is this when the issue is happening:

2018-03-16T11:20:49.544714-07:00  2018-03-16 11:20:49,544 [WARNING] polaris_health.tracker: failed to write generic state to the shared memory
2018-03-16T11:20:49.544788-07:00  2018-03-16 11:20:49,544 [WARNING] polaris_health.tracker: 0
2018-03-16T11:20:49.544893-07:00  2018-03-16 11:20:49,544 [WARNING] polaris_health.tracker: polaris_health:generic_state
2018-03-16T11:20:50.191790-07:00  2018-03-16 11:20:50,191 [WARNING] polaris_health.tracker: failed to write generic state to the shared memory
2018-03-16T11:20:50.191881-07:00  2018-03-16 11:20:50,191 [WARNING] polaris_health.tracker: 0
2018-03-16T11:20:50.191985-07:00  2018-03-16 11:20:50,191 [WARNING] polaris_health.tracker: polaris_health:generic_state
2018-03-16T11:20:50.868508-07:00  2018-03-16 11:20:50,868 [WARNING] polaris_health.tracker: failed to write generic state to the shared memory
2018-03-16T11:20:50.868582-07:00  2018-03-16 11:20:50,868 [WARNING] polaris_health.tracker: 0
2018-03-16T11:20:50.868696-07:00  2018-03-16 11:20:50,868 [WARNING] polaris_health.tracker: polaris_health:generic_state

Please let me know how I can troubleshoot this further or why it gets into this state.

**Comment by antongavrik** [comment]
What does "bin/polaris-memcache-control 127.0.0.1 get-generic-state |wc -c" output?

**Comment by mattackerman808** [comment]
$ bin/polaris-memcache-control get-generic-state |wc -c
2123921

**Comment by antongavrik** [comment]
Just a hypothesis, but it might be too large to fit into a single memcache write, polaris-health.yaml has the below configuration option (which also requires a change to the actual memcached configuration as well):
```
################################
# memcache SERVER_MAX_VALUE_LENGTH the maximum value length the memcached 
# will accept (memcached -I option)
#
# SHARED_MEM_SERVER_MAX_VALUE_LENGTH: 1048576
```

**Comment by mattackerman808** [comment]
Is that value in bytes? I will adjust it and see if it mitigates the warning.

**Comment by antongavrik** [comment]
Yes, as mentioned, it needs to be applied to both polaris and memcached.

**Comment by mattackerman808** [comment]
Thanks for your help.

Running memcached like so now (raised threads, max memory, max connections and max slab page size):

memcached -t 24 -p 11211 -u memcached -m 256 -c 2048 -P /var/run/memcached/memcached.pid -I 4m -d

Also made change in polaris-health.yaml:

################################
# memcache SERVER_MAX_VALUE_LENGTH the maximum value length the memcached
# will accept (memcached -I option)
#
SHARED_MEM_SERVER_MAX_VALUE_LENGTH: 4194304

Will report back with results.

**Comment by antongavrik** [comment]
Did it help?

**Comment by mattackerman808** [comment]
I took awhile to get this deployed into production fully. I haven't seen the error after the above mentioned changes. I think we can consider this resolved at this point.

Thanks again for your help (and the great software!)

**Comment by antongavrik** [comment]
Np. Polaris writes two state representations into memcache: 1) generic - can be used for monitoring and troubleshooting, has no impact on polaris operation, it has more data in it, such as backend server health failure reasons etc. and is larger than the second one 2) ppdns - the actual table used for query distribution, if you see that one is failing on writes it would be a critical error.
