### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mmontefl** [polaris-gslb/polaris-gslb#52]
This seems like an awesome project, but I dont see any activity and would like to use but am uncertain how to proceed. Is there anyone at the helm? 
I see direction to install on site and loadbalancer.com . I have done both ways and seem to work, though I havent fully tested transport.  I then thought, oh this DNS is facing Interwebz and see pDNS has lots of security patches, then thought, does this support 4.1.4?

**Comment by antongavrik** [comment]
#21

**Comment by mmontefl** [comment]
Ok, this can be closed. I see some but low interest. The potential here is big. I am surprised more dont use it
