### ISSUE TITLE
Python requirement

### ISSUE THREAD

**Issue by seitzbg** [polaris-gslb/polaris-gslb#9]
Why does this require 3.4.3+, is 3.4.2 broken?

TIA,

**Comment by antongavrik** [comment]
protocols/http.py has "UNVERIFIED_SSL_CONTEXT = ssl._create_unverified_context()", this method has been introduced somewhere in the 3.4.x 

Feel free to try it on 3.4.2 and let me know if it works.

Looking at https://www.python.org/dev/peps/pep-0476/, it says: 

"Additionally ssl._create_stdlib_context is renamed ssl._create_unverified_context (an alias is kept around for backwards compatibility reasons)."

So, perhaps, it's not to hard too fix for older versions of Python.

**Comment by seitzbg** [comment]
Yeah I will try with 3.4.2 unless I can get 3.4.3 or 3.5.0 SCL working :)
I will be deploying this so hopefully I can report success!

Thanks for your reply.

On Tue, Oct 27, 2015 at 01:22:09AM -0700, Anton Gavrik wrote:
> protocols/http.py has "UNVERIFIED_SSL_CONTEXT = ssl._create_unverified_context
> ()", this method has been introduced somewhere in the 3.4.x
> 
> Feel free to try it on 3.4.2 and let me know if it works.
> 
> Looking at https://www.python.org/dev/peps/pep-0476/, it says:
> 
> "Additionally ssl._create_stdlib_context is renamed
> ssl._create_unverified_context (an alias is kept around for backwards
> compatibility reasons)."
> 
> So, perhaps, it's not to hard too fix for older versions of Python.
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
             
Bryan G. Seitz

**Comment by antongavrik** [comment]
Closing as no further updates followed.
